[package]
name        = "bokit"
version     = "0.1.0"
authors     = ["Aurelien Naldi <aurelien.naldi@gmail.com>"]
description = "Boolean function manipulation Kit"
repository  = "https://github.com/GINsim/bokit/"
license     = "LGPL-3.0-or-later"
edition     = "2018"

[dependencies]
bit-set     = "0.5"
once_cell   = "1.8"
pest        = "2.1"
pest_derive = "2.1"
regex       = "1"
slab        = "0.4"
thiserror   = "1.0"


[dependencies.pyo3]
optional = true
version  = "0.14"
features = ["extension-module", "abi3", "abi3-py36"]

[lib]
crate-type = ["cdylib"]

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

